# Site settings
title: Lindsey McGovern
email: lindseymcgovern04@gmail.com
description: Passionate about ethical AI, live music, and making a positive impact through tech and leadership. # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://lindsey6214.github.io" # the base hostname & protocol for your site
github_username:  lindsey6214

# Build settings
markdown: kramdown

#advantage - globally accessible
# for e.g. site.title , site.email, site.url etc using Liquid template can be used anywhere
